# Site settings
title: Lee Clemmer
description: > # this means to ignore newlines until "baseurl:"
  Occasional writing on data-related topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leeclemmer.github.io" # the base hostname & protocol for your site
twitter_username: leeclemmer
github_username:  leeclemmer

# Build settings
markdown: kramdown
